image: debian:11

stages:
  - pylint
  - package
  - debrepo

variables:
  DISTR: buster
  DEB_OS_PREFIX: deb11
  APT_LOCAL_REPO: imedia-hpbx-testing-buster
  APT_REPO: imedia-hpbx-testing
  APT_DIR: imedia-hpbx-testing-${DISTR}
  PYTHON_BIN: python3
  PYTHON_PIP: pip3
  EMAIL: hpbxqateam@intermedia.net
  REQUIREMENTS: requirements.txt


.linter-default:pylint:
  stage: pylint
  tags: [python]
  allow_failure: true
  script:
    - apt-get update
    - ${PYTHON_BIN} -m pip install flake8
    - ${PYTHON_BIN} -m flake8  --max-line-length 120 src/

.create deb-default:package:
  stage: package
  tags: [python]
  before_script:
    - apt-get update 
    - apt-get install python3 python3-pip ruby ruby-dev rubygems build-essential -y
  artifacts:
    expire_in: 1 days
    paths:
      - "*deb"

.apt repo-default:debrepo:
  stage: debrepo
  tags: [python]
  script:
    - apt-get update
    - apt-get install -y curl
    - > 
      ls *.deb | while read l; do
      curl -X POST -F file=@"${l}"
      --user ${APTUSER}:${APTPASS} ${APTURL}/files/${APT_DIR};
      done
    - > 
      curl -X POST --user ${APTUSER}:${APTPASS}
      ${APTURL}/repos/${APT_LOCAL_REPO}/file/${APT_DIR}
    - > 
      curl -X PUT -H 'Content-Type:application/json'
      --data '{"Sources":[{"Component":"non-free"}],
      "Architectures":["amd64"], "Distribution":"${DISTR}"}'
      --user ${APTUSER}:${APTPASS} ${APTURL}/publish/${APT_REPO}/${DISTR}
  only:
    - tags


linter-deb10:pylint:
  stage: pylint
  image: python:3.7-stretch
  extends: .linter-default:pylint

linter-deb11:pylint:
  stage: pylint
  image: python:3.9.2-bullseye
  extends: .linter-default:pylint

create deb-deb10:package:
  image: debian:10
  script:
    - gem install --no-ri --no-rdoc fpm -v 1.11.0
    - >
      fpm  -s python
      --python-bin=${PYTHON_BIN}
      --python-pip=${PYTHON_PIP}
      --python-package-name-prefix=${PYTHON_BIN}
      -t deb  setup.py
  extends: .create deb-default:package

create deb-deb11:package:
  image: debian:11
  script:
    - gem install --no-document fpm -v 1.14.0
    - >
      fpm  -s python
      --python-bin=${PYTHON_BIN}
      --python-pip=${PYTHON_PIP}
      --python-package-name-prefix=${PYTHON_BIN}
      --replaces=${PYTHON_BIN}-${CI_PROJECT_NAME/_/-}
      --conflicts=${PYTHON_BIN}-${CI_PROJECT_NAME/_/-}
      --name=python3.9-${CI_PROJECT_NAME/_/-}
      -t deb  setup.py
  extends: .create deb-default:package

apt repo-deb10:debrepo:
  variables:
    DEB_OS_PREFIX: deb10
    DISTR: buster
    APT_LOCAL_REPO: imedia-hpbx-testing-${DISTR}
    APT_DIR: imedia-hpbx-testing-${DISTR}
  extends: .apt repo-default:debrepo
  dependencies:
    - create deb-deb10:package
  needs:
    - create deb-deb10:package

apt repo-deb11:debrepo:
  variables:
    DEB_OS_PREFIX: deb11
    DISTR: bullseye
    APT_LOCAL_REPO: imedia-hpbx-testing-${DISTR}
    APT_DIR: imedia-hpbx-testing-${DISTR}
  extends: .apt repo-default:debrepo
  dependencies:
    - create deb-deb11:package
  needs:
    - create deb-deb11:package
