image: debian:11

stages:
  - pylint
  - package
  - debrepo

variables:
  DISTR: buster
  DEB_OS_PREFIX: deb11
  APT_LOCAL_REPO: imedia-hpbx-testing-buster
  APT_REPO: imedia-hpbx-testing
  APT_DIR: imedia-hpbx-testing-buster
  PYTHON_BIN: python3
  PYTHON_PIP: pip3
  EMAIL: hpbxqateam@intermedia.net
  REQUIREMENTS: requirements.txt


linter:pylint:
  stage: pylint
  image: python:3.7-stretch
  tags: [python]
  allow_failure: true
  script:
    - apt-get update
    - ${PYTHON_BIN} -m pip install flake8
    - ${PYTHON_BIN} -m flake8  --max-line-length 120 src/


create deb:package:
  stage: package
  tags: [python]
  script:
    - apt-get update 
    - apt-get install python3 python3-pip ruby ruby-dev rubygems build-essential -y
    - gem install --no-ri --no-rdoc fpm
    - >
      fpm  -s python
      --python-bin=${PYTHON_BIN}
      --python-pip=${PYTHON_PIP}
      --python-package-name-prefix=${PYTHON_BIN}
      -t deb  setup.py
  artifacts:
    expire_in: 1 days
    paths:
      - "*deb"
  

apt repo:debrepo:
  stage: debrepo
  tags: [python]
  dependencies:
    - create deb:package
  script:
    - apt-get update
    - apt-get install -y curl
    - > 
      ls|grep "\.deb" | while read l; do
      curl -X POST -F file=@"${l}"  
      --user ${APTUSER}:${APTPASS} ${APTURL}/files/${APT_DIR};
      done
    - > 
      curl -X POST --user ${APTUSER}:${APTPASS} 
      ${APTURL}/repos/${APT_LOCAL_REPO}/file/${APT_DIR}
    - > 
      curl -X PUT -H 'Content-Type:application/json'  
      --data '{"Sources":[{"Component":"non-free"}], 
      "Architectures":["amd64"], "Distribution":"${DISTR}"}' 
      --user ${APTUSER}:${APTPASS} ${APTURL}/publish/${APT_REPO}/${DISTR}
  only:
    - tags
